// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqMKwONODyMp7sIVczzD6ZMtV9lkdmZnY',
    appId: '1:286394407264:web:ddfa1656208f8666bce605',
    messagingSenderId: '286394407264',
    projectId: 'proyectoluis-f7b29',
    authDomain: 'proyectoluis-f7b29.firebaseapp.com',
    storageBucket: 'proyectoluis-f7b29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABMZQbZvLKK8hNasK4XpHsh8kP03o31Rc',
    appId: '1:286394407264:android:522e553d1a4eba8ebce605',
    messagingSenderId: '286394407264',
    projectId: 'proyectoluis-f7b29',
    storageBucket: 'proyectoluis-f7b29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwpu6doWCuef7YpjeUl43vpz84PUM2bwg',
    appId: '1:286394407264:ios:390d179923e125c5bce605',
    messagingSenderId: '286394407264',
    projectId: 'proyectoluis-f7b29',
    storageBucket: 'proyectoluis-f7b29.appspot.com',
    iosClientId: '286394407264-48nf0r6bm6ope4cg4turcj2i7lb5k2gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiendaonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwpu6doWCuef7YpjeUl43vpz84PUM2bwg',
    appId: '1:286394407264:ios:390d179923e125c5bce605',
    messagingSenderId: '286394407264',
    projectId: 'proyectoluis-f7b29',
    storageBucket: 'proyectoluis-f7b29.appspot.com',
    iosClientId: '286394407264-48nf0r6bm6ope4cg4turcj2i7lb5k2gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiendaonline',
  );
}
